project:
  type: website
  output-dir: docs

website:
  favicon: images/leaf.png
  navbar:
    title: false
    logo: images/Picture5.png
    right: 
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: docs/bb-resume.pdf
        text: Resume
      - href: Blog.qmd
        text: Blog
  page-footer:
    background: light
    left: "Copyright 2023, Briana Barajas"
    right: 
      - icon : github
        href: https://github.com/briana-barajas
    
format:
  html:
    theme: 
      - styles.scss
    mainfont: Lato
    toc: true

editor: visual

