project:
  type: website
  output-dir: docs

website:
  title: "Briana B"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Experience
      - href: blog-page.qmd
        text: Blog

format:
  html:
    theme: Litera
    css: styles.css
    toc: true
    page-layout: full

editor: visual

