project:
  type: website
  output-dir: docs
website:
  title: "Briana B"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: docs/bb-resume.pdf
        text: Resume
      - href: Blog.qmd
        text: Blog
    page-footer:
      background: dark
      left: "Text Sample"
    
format:
  html:
    theme: 
      - styles.scss
    mainfont: Lato
    toc: true

editor: visual

