project:
  type: website
  output-dir: docs

website:
  title: "Briana Barajas"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Experience
      - href: resources.qmd
        text: Resources

format:
  html:
    theme: minty
    css: styles.css
    toc: true
    page-layout: full

editor: visual

